class GOST341194(object):
    def __init__(self, data: bytes = ..., sbox: str = ...) -> None: ...

    def update(self, data: bytes) -> None: ...

    def digest(self) -> bytes: ...

    def hexdigest(self) -> str: ...
