class GOST341112(object):
    def __init__(self, data: bytes = ..., digest_size: int = ...) -> None: ...

    def update(self, data: bytes) -> None: ...

    def digest(self) -> bytes: ...

    def hexdigest(self) -> str: ...
